import React from 'react';
import Head from "next/head";
import Link from "next/link";
import { makeStyles } from '@material-ui/core/styles';
import { Container, TextField, Typography, Button, Grid } from '@material-ui/core';

const useStyles = makeStyles((theme) => ({
    paper: {
        marginTop: theme.spacing(10),
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    form: {
        '& > *': {
            margin: theme.spacing(1),
            width: '40ch'
        },
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        marginTop: theme.spacing(1),
    },
    link: {
        textDecoration: 'none',
    }
}));

export default function Login() {
    const classes = useStyles();

    return (
        <React.Fragment>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <Container component="main" maxWidth="sm">
                    <div className={classes.paper}>
                        <Typography component="h1" variant="h5">
                            Log in
                        </Typography>
                        <form className={classes.form} noValidate>
                            <TextField
                                id="email"
                                type="email"
                                autoFocus
                                label="Email"
                                size="small"
                                variant="outlined" />
                            <TextField
                                id="password"
                                type="password"
                                label="Password"
                                size="small"
                                variant="outlined" />
                            <Button
                                type="submit"
                                fullWidth
                                variant="contained"
                                color="primary"
                            >
                                Log In
                            </Button>
                            <Grid container>
                                <Grid item xs={12}>
                                    <Link href="/auth/forgotpassword">
                                        <a className={classes.link}>
                                            Forgot password?
                                        </a>
                                    </Link>
                                </Grid>
                                <Grid item xs={12}>
                                    <Link href="/auth/signup">
                                        <a className={classes.link}>
                                            Don't have an account? Sign Up
                                        </a>
                                    </Link>
                                </Grid>
                            </Grid>
                        </form>
                    </div>
                </Container>
            </body>
        </React.Fragment>
    );
}
